/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectotpv;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alb19
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    DataBaseConnect dbc = new DataBaseConnect();
    DateFormat df = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    private int[] indiceMesas;
    private int[] indiceCamareros;
    
    
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date date = new Date();
            lblHoraYFecha.setText(df.format(date));
        }
    });
    
    public FormPrincipal() {
        initComponents();
        rellenarCmbCamarero();
        rellenarCmbMesa();
        borrarTabla();
        timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpciones = new javax.swing.JPanel();
        cmbCamarero = new javax.swing.JComboBox<>();
        cmbMesa = new javax.swing.JComboBox<>();
        btnAbrirTiquet = new javax.swing.JButton();
        chbTiquet = new javax.swing.JCheckBox();
        btnCargarTiquet = new javax.swing.JButton();
        pnlTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiquet = new javax.swing.JTable();
        lblHoraYFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNumTiquet = new javax.swing.JLabel();
        btnAñadeProducto = new javax.swing.JButton();
        btnQuitaProducto = new javax.swing.JButton();
        btnCerrarTiquet = new javax.swing.JButton();
        btnEliminaFilaTabla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotalTiquet = new javax.swing.JLabel();
        pnlTabProductos = new javax.swing.JTabbedPane();
        pnlComidas = new javax.swing.JPanel();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        pnlBebidas = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        pnlPostres = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        pnlAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbCamarero.setToolTipText("Elije camarero");
        cmbCamarero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCamareroActionPerformed(evt);
            }
        });

        cmbMesa.setToolTipText("Elije mesa");
        cmbMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesaActionPerformed(evt);
            }
        });

        btnAbrirTiquet.setText("Abrir tiquet");
        btnAbrirTiquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirTiquetActionPerformed(evt);
            }
        });

        chbTiquet.setText("Ocupada");
        chbTiquet.setEnabled(false);
        chbTiquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTiquetActionPerformed(evt);
            }
        });

        btnCargarTiquet.setText("Cargar Tiquet");
        btnCargarTiquet.setActionCommand("");
        btnCargarTiquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTiquetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbCamarero, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbTiquet)
                .addGap(18, 18, 18)
                .addComponent(btnAbrirTiquet, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCargarTiquet, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCamarero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrirTiquet)
                    .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbTiquet)
                    .addComponent(btnCargarTiquet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblTiquet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_producto", "id_tiquet", "Producto", "Precio/Unidad", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTiquet.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTiquet);
        if (tblTiquet.getColumnModel().getColumnCount() > 0) {
            tblTiquet.getColumnModel().getColumn(0).setMinWidth(0);
            tblTiquet.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblTiquet.getColumnModel().getColumn(0).setMaxWidth(0);
            tblTiquet.getColumnModel().getColumn(1).setMinWidth(0);
            tblTiquet.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblTiquet.getColumnModel().getColumn(1).setMaxWidth(0);
            tblTiquet.getColumnModel().getColumn(2).setResizable(false);
            tblTiquet.getColumnModel().getColumn(3).setResizable(false);
            tblTiquet.getColumnModel().getColumn(4).setResizable(false);
            tblTiquet.getColumnModel().getColumn(5).setResizable(false);
        }

        lblHoraYFecha.setText("jLabel2");

        jLabel1.setText("Numero de tiquet: ");

        btnAñadeProducto.setText("+");
        btnAñadeProducto.setToolTipText("Añadir 1");

        btnQuitaProducto.setText("-");
        btnQuitaProducto.setToolTipText("Quitar 1");

        btnCerrarTiquet.setText("CERRAR TIQUET");
        btnCerrarTiquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarTiquetActionPerformed(evt);
            }
        });

        btnEliminaFilaTabla.setText("ELIMINAR LA FILA SELECCIONADA");

        jLabel2.setText("Total tiquet: ");

        lblTotalTiquet.setText("lblTotalTiquet");

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTablaLayout.createSequentialGroup()
                                .addComponent(lblHoraYFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(pnlTablaLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumTiquet)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTablaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAñadeProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(btnQuitaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarTiquet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTablaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminaFilaTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(lblTotalTiquet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHoraYFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNumTiquet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminaFilaTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalTiquet))
                .addGap(16, 16, 16)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addComponent(btnAñadeProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuitaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCerrarTiquet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButton37.setText("jButton1");

        jButton38.setText("jButton1");

        jButton39.setText("jButton1");

        jButton40.setText("jButton1");

        jButton41.setText("jButton1");

        jButton42.setText("jButton1");

        jButton43.setText("jButton1");

        jButton44.setText("jButton1");

        jButton45.setText("jButton1");

        jButton46.setText("jButton1");

        jButton47.setText("jButton1");

        jButton48.setText("jButton1");

        javax.swing.GroupLayout pnlComidasLayout = new javax.swing.GroupLayout(pnlComidas);
        pnlComidas.setLayout(pnlComidasLayout);
        pnlComidasLayout.setHorizontalGroup(
            pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlComidasLayout.createSequentialGroup()
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlComidasLayout.createSequentialGroup()
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlComidasLayout.setVerticalGroup(
            pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComidasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pnlComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pnlTabProductos.addTab("Comidas", pnlComidas);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Coca-cola-light.jpg"))); // NOI18N
        jButton13.setText("jButton1");
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Coca-cola.jpg"))); // NOI18N
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Kas-limon.jpg"))); // NOI18N
        jButton15.setText("jButton1");
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_acuarius.jpg"))); // NOI18N
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Coca-cola-zero.jpg"))); // NOI18N
        jButton17.setText("jButton1");
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Fanta-naranja.jpg"))); // NOI18N
        jButton18.setText("jButton1");
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_nesteea.jpg"))); // NOI18N
        jButton19.setText("jButton1");
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Kas-naranja.jpg"))); // NOI18N
        jButton20.setText("jButton1");
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_agua-1,5l.jpg"))); // NOI18N
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_Fanta-limon.jpg"))); // NOI18N
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_agua 500ml.jpg"))); // NOI18N
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectotpv/imagen productos/Bebidas/mini_acuarius-naranja.jpg"))); // NOI18N
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlBebidasLayout = new javax.swing.GroupLayout(pnlBebidas);
        pnlBebidas.setLayout(pnlBebidasLayout);
        pnlBebidasLayout.setHorizontalGroup(
            pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBebidasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlBebidasLayout.createSequentialGroup()
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlBebidasLayout.createSequentialGroup()
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        pnlBebidasLayout.setVerticalGroup(
            pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBebidasLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                    .addGroup(pnlBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)))
        );

        pnlTabProductos.addTab("Bebidas", pnlBebidas);

        jButton25.setText("jButton1");

        jButton26.setText("jButton1");

        jButton27.setText("jButton1");

        jButton28.setText("jButton1");

        jButton29.setText("jButton1");

        jButton30.setText("jButton1");

        jButton31.setText("jButton1");

        jButton32.setText("jButton1");

        jButton33.setText("jButton1");

        jButton34.setText("jButton1");

        jButton35.setText("jButton1");

        jButton36.setText("jButton1");

        javax.swing.GroupLayout pnlPostresLayout = new javax.swing.GroupLayout(pnlPostres);
        pnlPostres.setLayout(pnlPostresLayout);
        pnlPostresLayout.setHorizontalGroup(
            pnlPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPostresLayout.createSequentialGroup()
                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPostresLayout.createSequentialGroup()
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPostresLayout.setVerticalGroup(
            pnlPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pnlPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pnlTabProductos.addTab("Postres", pnlPostres);

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTabProductos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTabProductos)
                        .addGap(3, 3, 3))
                    .addComponent(pnlAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesaActionPerformed
        // TODO add your handling code here:
        
        if(cmbMesa.getSelectedIndex() != 0 && cmbCamarero.getSelectedIndex() != 0){
            String nombreMesa = cmbMesa.getSelectedItem().toString();
            System.out.println(nombreMesa);
            boolean estado = dbc.comprobarMesa(nombreMesa);
            System.out.println(estado);
            System.out.println(cmbMesa.getSelectedIndex());
            chbTiquet.setSelected(estado);
            btnAbrirTiquet.setEnabled(!estado);
            btnCargarTiquet.setEnabled(estado);
            int num = dbc.compruebaTiquet(indiceMesas[cmbMesa.getSelectedIndex()], indiceCamareros[cmbCamarero.getSelectedIndex()]);
            if(num != 0){
                lblNumTiquet.setText(String.valueOf(num));
            }else{
                lblNumTiquet.setText("");
            }
        }
 
    }//GEN-LAST:event_cmbMesaActionPerformed

    private void chbTiquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTiquetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_chbTiquetActionPerformed

    private void btnCargarTiquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTiquetActionPerformed
        // TODO add your handling code here:
        if(!"".equals(lblNumTiquet.getText())){
            actualizarTabla(Integer.parseInt(lblNumTiquet.getText()));
        }
        
    }//GEN-LAST:event_btnCargarTiquetActionPerformed

    private void btnAbrirTiquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirTiquetActionPerformed
        // TODO add your handling code here:
        if(dbc.crearTiquet(indiceMesas[cmbMesa.getSelectedIndex()], indiceCamareros[cmbCamarero.getSelectedIndex()])){
            lblNumTiquet.setText(String.valueOf(dbc.compruebaTiquet(indiceMesas[cmbMesa.getSelectedIndex()], indiceCamareros[cmbCamarero.getSelectedIndex()])));
            btnAbrirTiquet.setEnabled(true);
        }
    }//GEN-LAST:event_btnAbrirTiquetActionPerformed

    private void cmbCamareroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamareroActionPerformed
        // TODO add your handling code here:
        if(cmbMesa.getSelectedIndex() != 0 && cmbCamarero.getSelectedIndex() != 0){
            String nombreMesa = cmbMesa.getSelectedItem().toString();
            System.out.println(nombreMesa);
            boolean estado = dbc.comprobarMesa(nombreMesa);
            System.out.println(estado);
            System.out.println(cmbMesa.getSelectedIndex());
            chbTiquet.setSelected(estado);
            btnAbrirTiquet.setEnabled(!estado);
            btnCargarTiquet.setEnabled(estado);
            int num = dbc.compruebaTiquet(indiceMesas[cmbMesa.getSelectedIndex()], indiceCamareros[cmbCamarero.getSelectedIndex()]);
            if(num != 0){
                lblNumTiquet.setText(String.valueOf(num));
            }else{
                lblNumTiquet.setText("");
            }
        }
    }//GEN-LAST:event_cmbCamareroActionPerformed

    private void btnCerrarTiquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarTiquetActionPerformed
        // TODO add your handling code here:
        boolean cerrado;
        if(!lblNumTiquet.getText().equals("")){
            cerrado = dbc.cerrarTiquet(Integer.parseInt(lblNumTiquet.getText()));
            if(cerrado){
                System.out.println("Cerrado!");
                btnAbrirTiquet.setEnabled(!cerrado);
                btnCerrarTiquet.setEnabled(cerrado);
                lblNumTiquet.setText("");
                lblTotalTiquet.setText("0.0");
                borrarTabla();
            }
            else System.out.println("Error!");
        }else{
            System.out.println("No hay tiquet para cerrar!");
        }
    }//GEN-LAST:event_btnCerrarTiquetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }
    
    private void rellenarCmbCamarero(){
        cmbCamarero.removeAllItems();
        try {
            // TODO add your handling code here:
            ResultSet r = dbc.cargaCamareros();
            r.last();
            indiceCamareros = new int[r.getRow() + 1];
            r.beforeFirst();
            cmbCamarero.addItem("Elije camarero");
            indiceCamareros[0] = 0;
            int i = 1;
            while(r.next()){
                indiceCamareros[i] = r.getInt("id");
                cmbCamarero.addItem(r.getString("nombre") + " " + r.getString("primer_ape"));
                i++;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void rellenarCmbMesa(){
        cmbMesa.removeAllItems();
        try {
            // TODO add your handling code here:
            ResultSet r = dbc.cargaMesas();
            r.last();
            indiceMesas = new int[r.getRow() + 1];
            r.beforeFirst();
            cmbMesa.addItem("Elije mesa");
            indiceMesas[0] = 0;
            int i = 1;
            while(r.next()){
                indiceMesas[i] = r.getInt("id");
                cmbMesa.addItem(r.getString("nombre"));
                i++;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void actualizarTabla(int idTiquet){
        ResultSet r = dbc.getDatosTabla(idTiquet);
        //tblTiquet.removeAll();
        DefaultTableModel miModelo = (DefaultTableModel) tblTiquet.getModel();
        int reg = Integer.parseInt(String.valueOf(tblTiquet.getRowCount()));
        //System.out.println(r.last()+ " " + r.getRow());
        for(int i = reg - 1; i >= 0; i--){
            //System.out.println(r.last()+ " " + r.getRow());
            miModelo.removeRow(i);
        }
        float totalTiquet = 0;
        try {
            r.beforeFirst();
            while(r.next()){
                Object[] filas = new Object[6];
                filas[0] = String.valueOf(r.getInt("id_tiquet"));
                filas[1] = String.valueOf(r.getInt("id_producto"));
                filas[2] = r.getString("nombre_producto");
                filas[3] = String.valueOf(r.getFloat("precio_unidad"));
                filas[4] = String.valueOf(r.getInt("cantidad"));
                filas[5] = String.valueOf(r.getFloat("total"));
                totalTiquet += Float.parseFloat(String.valueOf(filas[5]));
                miModelo.addRow(filas);
                //tblTiquet.setModel(miModelo);

            }
            DecimalFormat df = new DecimalFormat("#.00");
            System.out.println(df.format(totalTiquet));
            lblTotalTiquet.setText(String.valueOf(df.format(totalTiquet)));
            tblTiquet.setModel(miModelo);

        } catch (SQLException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void borrarTabla(){
        DefaultTableModel miModelo = (DefaultTableModel) tblTiquet.getModel();
        
        int reg = Integer.parseInt(String.valueOf(tblTiquet.getRowCount()));
            //System.out.println(r.last()+ " " + r.getRow());
            for(int i = reg - 1; i >= 0; i--){
                //System.out.println(r.last()+ " " + r.getRow());
                miModelo.removeRow(i);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirTiquet;
    private javax.swing.JButton btnAñadeProducto;
    private javax.swing.JButton btnCargarTiquet;
    private javax.swing.JButton btnCerrarTiquet;
    private javax.swing.JButton btnEliminaFilaTabla;
    private javax.swing.JButton btnQuitaProducto;
    private javax.swing.JCheckBox chbTiquet;
    private javax.swing.JComboBox<String> cmbCamarero;
    private javax.swing.JComboBox<String> cmbMesa;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHoraYFecha;
    private javax.swing.JLabel lblNumTiquet;
    private javax.swing.JLabel lblTotalTiquet;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlBebidas;
    private javax.swing.JPanel pnlComidas;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlPostres;
    private javax.swing.JTabbedPane pnlTabProductos;
    private javax.swing.JPanel pnlTabla;
    private javax.swing.JTable tblTiquet;
    // End of variables declaration//GEN-END:variables
}
